### PR TITLE
Update

### PR DESCRIPTION
**Pull request by Justman100**

### CODE REVIEW

**Comment by Justman100** [comment]
@VojtaStruhar

**Review by VojtaStruhar — COMMENTED** [review]
Thanks for the update!

**Review by VojtaStruhar — CHANGES_REQUESTED** [review]
Thanks for the updated dependencies!

However please, [do not delete the lock file](https://pnpm.io/git)! :)

**Comment by Justman100** [comment]
> Thanks for the updated dependencies!
> 
> However please, [do not delete the lock file](https://pnpm.io/git)! :)

Fixed

**Review by VojtaStruhar — APPROVED** [review]

**Comment by VojtaStruhar** [comment]
Thanks and congratulations for a merged PR! 👍

**Pull request merged**
